# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - '*'     # build all branches
  paths:
    exclude:
    - docs/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    steps:
    - template: build.yml
      parameters:
        buildConfiguration: 'Debug'

    - template: build.yml
      parameters:
       buildConfiguration: 'Release'

    - task: PublishBuildArtifacts@1 
      displayName: 'Publish Artifact: drop'
      condition: succeeded()

- stage: 'Test'
  displayName: 'Deploy to Test Environment'
  dependsOn: Build
  condition: |
      succeeded()
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-16.04'
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            inputs: 
              azureSubscription: 'Free Trial(8dfda198-2640-4876-aa65-25ef40a829b1)'
              appType: 'webAppLinux'
              appName: '$(WebAppNameTest)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
              runtimeStack: 'DOTNETCORE|2.0'