parameters:
- name: buildConfiguration # name of the parameter; required
  type: string # data type of the parameter; required
  default: 'Release'

- script: dotnet build --configuration ${{parameters.buildConfiguration}}
  displayName: 'dotnet build ${{parameters.buildConfiguration}}'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - ${{parameters.buildConfiguration}}'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${{parameters.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)/${{parameters.buildConfiguration}}'
    zipAfterPublish: truegit 